import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { auth } from "@/lib/auth";
import { resolveStore } from "@/lib/store";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ store: string; id: string }> }
) {
  const { store: storeSlug, id } = await params;
  const store = await resolveStore(storeSlug);
  if (!store) {
    return NextResponse.json({ error: "Store not found" }, { status: 404 });
  }

  const session = await auth();
  if (!session?.user || session.user.role !== "PHARMACY_ADMIN") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const invoice = await prisma.invoice.findUnique({
    where: { id, storeId: store.id },
    include: {
      lineItems: { include: { order: true } },
      generatedBy: true,
      driver: true,
    },
  });

  if (!invoice) {
    return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
  }

  // Generate PDF
  const doc = new jsPDF();

  // Header — include store name
  doc.setFontSize(20);
  doc.text(store.name, 14, 22);
  doc.setFontSize(10);
  doc.text("Delivery Invoice", 14, 30);

  doc.setFontSize(12);
  doc.text(`Invoice: ${invoice.invoiceNumber}`, 14, 45);
  doc.setFontSize(10);
  doc.text(
    `Period: ${new Date(invoice.periodStart).toLocaleDateString()} – ${new Date(invoice.periodEnd).toLocaleDateString()}`,
    14,
    52
  );
  doc.text(`Generated: ${new Date(invoice.createdAt).toLocaleDateString()}`, 14, 58);
  doc.text(`Generated by: ${invoice.generatedBy.name}`, 14, 64);
  doc.text(`Driver: ${invoice.driver?.name ?? "Unassigned"}`, 14, 70);

  // Table
  const tableData = invoice.lineItems.map((item, i) => [
    i + 1,
    new Date(item.order.scheduledDate).toLocaleDateString(),
    item.order.patientName,
    item.description,
    `$${item.amount.toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 78,
    head: [["#", "Date", "Patient", "Description", "Amount"]],
    body: tableData,
    foot: [["", "", "", "Total", `$${invoice.totalAmount.toFixed(2)}`]],
    theme: "striped",
    headStyles: { fillColor: [37, 99, 235] },
    footStyles: { fillColor: [243, 244, 246], textColor: [0, 0, 0], fontStyle: "bold" },
  });

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

  return new NextResponse(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${invoice.invoiceNumber}.pdf"`,
    },
  });
}
